### ISSUE TITLE
Control closing the menu if clicking outside

### ISSUE THREAD

**Issue by stevenfitzpatrick** [paypal/downshift#444]
* `downshift` version: 1.31.14
* `node` version: 9
* `npm` (or `yarn`) version: 1.6.0

I'm looking for a way to prevent the menu from closing when clicking outside the menu.

Right now when you click outside the menu , handleToggle is always called and `isOpen` set to false closing the menu. I'm looking to prevent this where I want to actually keep the menu open in some cases , is there anyway to achieve this ?

```javascript
handleToggle = ({ isOpen, type }) => {
    this.setState({ open: isOpen })
}

<Downshift
   defaultIsOpen={open}
   isOpen={open}
   onStateChange={this.handleToggle}
```

**Comment by kentcdodds** [comment]
Hi! Look at the docs for how to use the stateReducer 👌

**Comment by stevenfitzpatrick** [comment]
Thanks for the reply, that does help me get on the right track.

However for a full solution I do need to get access to the `event.target` of the `click`/`mouseup` event which Downshift doesn't seem to return. Do you know any work around to get the `event` returned ?

**Comment by kentcdodds** [comment]
Could you help us understand why you need the event?

**Comment by green-arrow** [comment]
I'm not the original poster, but I have what might be a similar issue. On mobile, we render the dropdown menu items in a portal. This means that detecting if `event.target` is inside of `_rootNode` will always be `false` when selecting a menu item, since all menu items are in a portal outside of the root node.

We could look at the `type` and just ignore the `touchstart` event type, but I'm wondering if there's another solution such as not calling reset if the target is a menu item, even if not contained in `_rootNode`.

**Comment by kentcdodds** [comment]
Ah, this will be resolved with this: https://github.com/paypal/downshift/issues/287

I just need to carve out enough time to work on downshift 2.0.0 which should hopefully be in the next week or two.

**Comment by kentcdodds** [comment]
downshift@2.0.0 has had a beta release and this has been fixed in there I believe. Please see #461 for more information on how to try it out! The official release will come soon.

**Comment by green-arrow** [comment]
@kentcdodds  - Sorry for not testing this out sooner! I just pulled down `2.0.9`, but I"m still having this issue. I've applied `getMenuProps` to my `ul` which is in a portal, and `reset` is still triggered.

Looking at the code, it seems like `this._menuNode` is only being used in determining if the event happened inside of downshift on mouse up. The `onTouchStart` event still only uses `this._rootNode`.

Reference: https://github.com/paypal/downshift/blob/master/src/downshift.js#L937-L945

Was it intentional to not use `this._menuNode` in the `onTouchStart` event? If not, I can issue a PR with the change.

**Comment by kentcdodds** [comment]
Yup, that was an oversight on my part. I'd love a PR :) Thanks!

**Comment by mnpenner** [comment]
I'm having a similar issue, but I don't understand the solution here.

My component looks like this: ![](https://i.imgur.com/F8iOU4G.png)

I want it so that when you click on the `<input>`, it *won't* close, but if you click outside then it will. I'm also using a portal.

I've prevented the closing with a `stateReducer`:

```ts
function stateReducer(state: DownshiftState<Item>, changes: StateChangeOptions<Item>) {
    console.log('state:',state, 'changes:',changes);
    switch (changes.type) {
        case Downshift.stateChangeTypes.mouseUp:
            return {};
        default:
            return changes;
    }
}
```

But now it won't close when I click outside either. What's the solution?

**Comment by mattbf** [comment]
For anyone running into this, I solved it like so: 

_Not the most elegant, I couldn't make it work with the `stateReducer` from downshift because there is no state change for clicking outside of the menu, only blurring the input._ 

My use case was I wanted to add a "select/deselect" all button beside the input that would keep the menu open when clicking on it. 
![CleanShot 2024-02-08 at 11 22 25](https://github.com/downshift-js/downshift/assets/48523927/95d4d793-64a5-4211-a316-957cdf1842da)

In order to differentiate between clicking the button (blurring the input → keeping the menu OPEN) and clicking outside of the menu (blurring input → CLOSING the keeping) I 

1. Added refs to both the button and the input
2. In my state reducer, added logic for `input blur && focusedElementIsButton` to keep the menu open
3. Refocused the input in the button onClick handler.

```ts
 stateReducer(_state, actionAndChanges) {
      const { changes, type } = actionAndChanges;

      switch (type) {
        case useCombobox.stateChangeTypes.InputBlur:
          const isButtonFocused = document.activeElement === buttonRef.current;
          return {
            ...changes,
            isOpen: isButtonFocused, //close the menu ONLY if the close event wasn't my select all button
          };
        case useCombobox.stateChangeTypes.InputClick:
          return {
            ...changes,
            isOpen: true, //keep the input open when you click on it
          };
        case useCombobox.stateChangeTypes.InputKeyDownEnter:
        case useCombobox.stateChangeTypes.ItemClick:
          return {
            ...changes,
            inputValue: '', //don't filter the list
            isOpen: true, // keep the menu open after selection.
          };
        default:
          return changes;
      }
    }
```

Again, not the most elegant, but if I'm missing something or there is a better way let me know.
